// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Done: typeof import('./src/components/Done.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    Upload: typeof import('./src/components/Upload.vue')['default']
    Uploading: typeof import('./src/components/Uploading.vue')['default']
    Waiting: typeof import('./src/components/Waiting.vue')['default']
    Wallpapers: typeof import('./src/components/Wallpapers.vue')['default']
  }
}
